name: iirjdart
description: A new Flutter package.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  complex: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

